version: '3.1'

services:
  database:
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ledgero
    ports:
      - "5470:5432"

  memcached:
    image: docker.io/memcached
    restart: always

  backend:
    image: ledgero-api
    restart: always
    ports:
      - "5050:8000"
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
      DATABASE_URL: postgres://test:test@database:5432/ledgero
      MEMCACHED_URL: memcache://memcached:11211
      PRIVATE_PEM_PATH: /jwtRS256.key
      JWT_ACCESS_EXPIRE_SECONDS: 3600
      JWT_REFRESH_EXPIRE_SECONDS: 7776000
      JWT_ISSUER: ledgero-ui-dev
      MAX_BLOB_UNCONFIRMED: 300
      SCHEDULER_INTERVAL_SECONDS: 300
      RUST_LOG: trace,sqlx=warn,_=off
    volumes:
      - type: bind
        source: ./jwtRS256.key
        target: /jwtRS256.key
