version: '3.1'

services:
  database:
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: piggybanks
    ports:
      - "5470:5432"

  backend:
    image: piggybanks-rust
    restart: always
    ports:
      - "5000:8000"
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
      DATABASE_URL: postgres://test:test@database:5432/piggybanks
      PRIVATE_PEM_PATH: /jwtRS256.key
      JWT_EXPIRE_SECONDS: 3600
      JWT_ISSUER: piggybanks-ui-dev
    volumes:
      - type: bind
        source: ./jwtRS256.key
        target: /jwtRS256.key
